# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colores.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem
from PyQt5.QtGui import QPainter, QColor, QPen

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 150, 601, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 70, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.meter)
        self.f = 8



    def meter(self):
        # rowPosition = self.tableWidget.rowCount()
        # self.tableWidget.insertRow(rowPosition)
        # colum = self.tableWidget.columnCount()
        # self.tableWidget.insertColumn(colum)
        # self.tableWidget.setItem(rowPosition,0,QTableWidgetItem('hola'))
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        colum = self.tableWidget.columnCount()
        self.tableWidget.insertColumn(colum)
        x = int(self.lineEdit.text())
        rowPosition = self.tableWidget.rowCount()
        
        
        #rowPosition = row position
        #self.f = colum position
        self.f=0
        self.tableWidget.insertRow(rowPosition)
        for a in range(x):
            if a ==10:
                self.tableWidget.setItem(rowPosition,self.f, QTableWidgetItem(str(a)))
                self.tableWidget.item(rowPosition,self.f).setBackground(QtGui.QColor('red'))
                
            if a !=10:
                self.tableWidget.setItem(rowPosition,self.f, QTableWidgetItem(str(a)))
            self.f = self.f + 1
            
            if self.f == 7:
                self.f = 0
                rowPosition = self.tableWidget.rowCount()
                self.tableWidget.insertRow(rowPosition)
       


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
