# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtnCantidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtnCantidad(object):
    def setupUi(self, vtnCantidad):
        vtnCantidad.setObjectName("vtnCantidad")
        vtnCantidad.setWindowModality(QtCore.Qt.NonModal)
        vtnCantidad.resize(211, 162)
        vtnCantidad.setMinimumSize(QtCore.QSize(211, 162))
        vtnCantidad.setMaximumSize(QtCore.QSize(211, 162))
        vtnCantidad.setMouseTracking(False)
        vtnCantidad.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagenes/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        vtnCantidad.setWindowIcon(icon)
        vtnCantidad.setAccessibleName("")
        vtnCantidad.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size: 15px;\n"
"}\n"
"#vtnCantidad{\n"
" background:#fefefe;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"background:#ffc001;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#dea806;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom: 1px solid black;\n"
"    background:transparent;\n"
"}\n"
"\n"
"")
        vtnCantidad.setSizeGripEnabled(False)
        vtnCantidad.setModal(False)
        self.label = QtWidgets.QLabel(vtnCantidad)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.label.setObjectName("label")
        self.btnAceptardialogSalida = QtWidgets.QPushButton(vtnCantidad)
        self.btnAceptardialogSalida.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.btnAceptardialogSalida.setObjectName("btnAceptardialogSalida")
        self.LineCantidaddialogSalida = QtWidgets.QLineEdit(vtnCantidad)
        self.LineCantidaddialogSalida.setGeometry(QtCore.QRect(40, 60, 151, 31))
        self.LineCantidaddialogSalida.setObjectName("LineCantidaddialogSalida")
        self.btnCancelardialogSalida = QtWidgets.QPushButton(vtnCantidad)
        self.btnCancelardialogSalida.setGeometry(QtCore.QRect(110, 110, 91, 31))
        self.btnCancelardialogSalida.setObjectName("btnCancelardialogSalida")

        self.retranslateUi(vtnCantidad)
        QtCore.QMetaObject.connectSlotsByName(vtnCantidad)
        vtnCantidad.setTabOrder(self.LineCantidaddialogSalida, self.btnAceptardialogSalida)
        vtnCantidad.setTabOrder(self.btnAceptardialogSalida, self.btnCancelardialogSalida)

    def retranslateUi(self, vtnCantidad):
        _translate = QtCore.QCoreApplication.translate
        vtnCantidad.setWindowTitle(_translate("vtnCantidad", "Cantidad"))
        self.label.setText(_translate("vtnCantidad", "<html><head/><body><p><span style=\" font-size:14pt;\">¿Cuánto Desea?</span></p></body></html>"))
        self.btnAceptardialogSalida.setText(_translate("vtnCantidad", "Aceptar"))
        self.btnAceptardialogSalida.setShortcut(_translate("vtnCantidad", "Return"))
        self.btnCancelardialogSalida.setText(_translate("vtnCantidad", "Cancelar"))
        self.btnCancelardialogSalida.setShortcut(_translate("vtnCantidad", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtnCantidad = QtWidgets.QDialog()
    ui = Ui_vtnCantidad()
    ui.setupUi(vtnCantidad)
    vtnCantidad.show()
    sys.exit(app.exec_())
